### ISSUE TITLE
運行一些時間後會crash

### ISSUE THREAD

**Issue by yuessir** [NTUT-SELab/MicrosoftGraphBot#22]
**描述錯誤**
運行約一周後會整個console 拋紅字

**重現**
重現該行為的步驟：
click後運行
**預期的行為**
請簡潔明了的描述，您期望發生的事情。

 **屏幕截圖**

**其他上下文**

哪邊可以看到dump log?

**Comment by ChengYen-Tang** [comment]
程式資料夾下，可以看到 Logs 資料集

**Comment by ChengYen-Tang** [comment]
出現紅字，但應該沒有 Crash 吧?
如果呼叫 Api 失敗會出現紅字
目前知道 叫到 Calendar 的 Api 會失敗

**Comment by yuessir** [comment]
@ChengYen-Tang 我觀察一下 目前是看到連不上DB服務 如果沒有問題我會關閉這個issue Thanks :)
